### ISSUE TITLE
Warning: Illegal string offset 'exponent'

### ISSUE THREAD

**Issue by GieltjE** [spotweb/spotweb#246]
Environment:
 - Gentoo 4.8.11-hardened
 - PHP 7.1.0
 - MariaDB 10.1.19
 - Call via bash --> /usr/bin/php spotweb/retrieve.php

Warning: Illegal string offset 'exponent' in spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31
PHP Warning:  Illegal string offset 'exponent' in spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 38

**Comment by GeoffreyDijkstra** [comment]
I just looked into this issue for someone else. Can you check which version
of openssl you are running on your system?

Op 19 dec. 2016 11:46 schreef "Michiel Hazelhof" <notifications@github.com>:

Environment:

   - Gentoo 4.8.11-hardened
   - PHP 7.1.0
   - MariaDB 10.1.19
   - Call via bash --> /usr/bin/php spotweb/retrieve.php

Warning: Illegal string offset 'exponent' in
spotweb/lib/services/Signing/Services_Signing_Openssl.php
on line 31
PHP Warning: Illegal string offset 'exponent' in
spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php
on line 38

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/spotweb/spotweb/issues/246>, or mute the thread

**Comment by GieltjE** [comment]
Stupid me, should have posted it, 1.0.2j, noted on the top post as wel.

Everything has been compiled against the correct versions.

**Comment by GeoffreyDijkstra** [comment]
@GieltjE Since when do you have this error? Only after today or did you just setup a new spotweb install?

**Comment by GieltjE** [comment]
For about two weeks since I ran a git pull. The installation is a few years old and was running just fine.

If I feel a bit better I might try reverting git patches tonight.

**Comment by GeoffreyDijkstra** [comment]
That would be great!
And since when are running PHP 7.1?

**Comment by GieltjE** [comment]
About the same time, so compiling an older version will be another test

**Comment by dterweij** [comment]
Issue #243 is closed as it is resolved. But still there are problems.
I dont have comments. They are counted on the frontpage but nothing is showed inside the spot. Also the spotpicture is not loading.

I am glad tho that it sends the NZB to SAB. So that part is fine :)  But in general, there are more problems to be solved....

**Comment by dterweij** [comment]
...might just be some OS packages that needs new versions then spotweb coding faults....

**Comment by GieltjE** [comment]
Downgrade to PHP 7.0.14 seems to fix all isues, maybe there should be a generic PHP7.1 compat issue? Might keep users from opening up individual issues.

**Comment by GeoffreyDijkstra** [comment]
I know that it works with PHP 7.0, but I wonder why it's breaking with 7.1. And people never see if there already is an existing issue :wink: 

@dterweij I would agree if it would only affect 1 person.
I'm currently setting up a second environment with PHP7.1 to see if I can reproduce it there.

**Comment by mesa57** [comment]
@GeoffreyDijkstra : is there already a rtm version of php 7.1 (for windows). If so, I can update my DEV environment ?

**Comment by GeoffreyDijkstra** [comment]
@dterweij @GieltjE A complicated workaround could be to keep PHP 7.0 or 7.1 for all sites except spotweb: Install multiple PHP versions with php-fpm (preferred or mod_php) and setup apache to use 7.0 (or 7.1) as default and overwrite it in a vhost for spotweb (set it to 5.6?).

**Comment by GeoffreyDijkstra** [comment]
@mesa57 http://windows.php.net/qa/ There are binaries.

**Comment by mesa57** [comment]
Ok, thx for the link 😄

**Comment by GeoffreyDijkstra** [comment]
Your welcome :wink:
But why on earth run it on windows :smile: 

I'm currently running multiple PHP versions with PHP-FPM strange thing is that on my laptop with ubuntu and PHP 7.1 I don't have errors.

**Comment by GieltjE** [comment]
The webui runs fine with 7.1, it's the retrieve.php script which is broken. (FPM doesn't come into play here usually).

**Comment by mesa57** [comment]
I run on windows, because I use visual studio as dev tool.
I worked a period with php/eclipse on unix, but only found it cumbersome.

**Comment by GeoffreyDijkstra** [comment]
@mesa57 Try PHPStorm, its available for windows and linux. Same idea as
visual studio only optimized for PHP.

Op 19 dec. 2016 17:00 schreef "mesa57" <notifications@github.com>:

**Comment by dterweij** [comment]
Another one:   vendor pCharts, this software is old and guess?  also dont like PHP 7.1. But as I also used pChart for other things, I replaced it with the google Chart API. Much nicer graphs. I suggest to thow away the pChart libs and use google Charts API.

`PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in /home/danny/public_html/spotweb/vendor/jean-damien/pchart/class/pData.class.php:80`

**Comment by dterweij** [comment]
p.s. I don't mind that spotweb is at this moment working a little bit. It gets spots, and I can get the NZB's to SAB.  The retrieve.php is not finishing, ends with stacktrace, thats why I think it does not get comments. When I run check-cache.php, It gets images and NZB's. Never seen that before as I thought the tool did not work :P I have faith and patience that the developers of Spotweb gets it all fine again. 
I have to say, there are always people running fresh bleeding edge software. Each PHP version sucks in my eyes, every new version does have a high impact of changes. 
It is a pain in the ass for some systems to roll back a PHP version. Done that, did not like that, dont do that anymore. RH based systems don't like it. Same for updating openssl 1.0.1e-48 to 1.0.2 ... you have to rebuild a lot system packages yourself with 1.0.2.  There is a reason why there is still a openssl098 package in stock.... Tho I removed it and got no problems so far :P  

Everyone nice xmas days... not much online still after xmas :)

**Comment by GeoffreyDijkstra** [comment]
@dterweij Well of course it requires more work 😄 

Jij ook prettige kerstdagen en alvast een mooi 2017 😉

**Comment by mesa57** [comment]
Interesting survey of php usage : 
https://w3techs.com/technologies/details/pl-php/5/all
Php 5.2 and 5.3 are still in majority !

**Comment by GeoffreyDijkstra** [comment]
@mesa57 That's interesting to see, but 1. That means the largest part of the world has security issues, because [PHP < 5.6 isn't supported anymore](http://php.net/supported-versions.php). Which imho means that we don't need to support that anymore (I also understand your point of view). Also I wonder how they detect the php version, because if configured correctly PHP doesn't expose it's version to the webserver.

**Comment by Sweepr** [comment]
@GeoffreyDijkstra here's another, + a brief explanation on how the data is gathered.

https://seld.be/notes/php-versions-stats-2016-1-edition.

Altough this version gathered around May 2016 shows:

All versions 			Grouped 	
PHP 5.5.9 	11.87% 		PHP 5.6 	39.67%
PHP 7.0.6 	10.39% 		PHP 5.5 	29.56%
PHP 5.6.20 	8.41% 		PHP 7.0 	20.24%
PHP 5.6.21 	7.69% 		PHP 5.4 	7.64%
PHP 5.6.19 	4.71% 		PHP 5.3 	2.43%

**Comment by dsadsdadsadsadsds** [comment]
Just a heads up -- Spotweb takes very much care to never connect as the USER visiting the Spotweb site (of course, the Spotweb server side cannot prevent this :smile: ) so Google Charts is not a good choice.

(this is, i think, also the reason we always use ```?page=getspotimage``` instead of directly accessing the images)

**Comment by mesa57** [comment]
Images are retrieve from usenet (in gzip format). They cannot be directly accessed.

**Comment by dsadsdadsadsadsds** [comment]
IIRC in very early Spotnet versions, it included an HTTP link to the image, but you probably know this better than i do

**Comment by mesa57** [comment]
That's correct. It was a protocol change around 2012

**Comment by dsadsdadsadsadsds** [comment]
With regards to the offset error @GieltjE is getting my guess would be that the XML parsing is somehow broken or we are being fed corrupt Spotnet headers.

A possibility might be to run retrieve in ```--debug``` mode to see which of the message-id's return an notice and then to see if @GeoffreyDijkstra's version returns the same error.

Another change might be to temporarily disable the OpenSSL extension -- Spotweb should then fallback to the awfully slow openssl emulation library and this rules out the openssl extension completely.

Are you up to this, @GieltjE ?

**Comment by GieltjE** [comment]
Yeah, I'll probably end up doing these tests just before the end of this year, it's getting kinda hectic right now.

**Comment by GieltjE** [comment]
Without the ssl compile flag the following occurs:
PHP Warning:  stream_socket_client(): unable to connect to ssl://<server>:563 (Unable to find the socket transport "ssl" - did you forget to enable it when you configured PHP?) in /var/www/spotweb/vendor/gdwebs/nntp/src/Protocol/Client.php on line 725

**Comment by GieltjE** [comment]
With debug

Retrieving 2987138 till 2987730PHP Notice:  A non well formed numeric value encountered in /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php on line 103

Notice: A non well formed numeric value encountered in /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php on line 103
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 38

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 38
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 39

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 39
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31
PHP Notice:  A non well formed numeric value encountered in /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php on line 103

The notices and warnings repeat

**Comment by mesa57** [comment]
Resolved in latest commit.

**Comment by GieltjE** [comment]
Don't know if it's related but still some error's appear on php 7.1.1

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 38
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 39

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 39
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25

Warning: Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 25
PHP Warning:  Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30

Warning: Illegal string offset 'modulo' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 30
PHP Warning:  Illegal string offset 'exponent' in /var/www/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 31

**Comment by mesa57** [comment]
Sorry about closing this issue, opening again.

**Comment by rschu68** [comment]
Downgrading to version 7.0.14 does work
https://www.ostechnix.com/downgrade-package-arch-linux/
https://wiki.manjaro.org/index.php?title=Using_Downgrade

**Comment by mesa57** [comment]
Solved in last commit. Please reopen if not.

**Comment by Rouzax** [comment]
I'm still getting this message in my php error log.

OS: Server 2016
PHP 7.1.1 X64
Spotweb: 681c8e95fd96ed21ac7de66aba1f6bc9b486459d

```
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisDisplay' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 73
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisFormat' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 74
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 74
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisName' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 75
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 75
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisUnit' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 76
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 76
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'Abscissa' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 77
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 77
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'AbsicssaPosition' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 78
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'Axis' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 80
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php:80
Stack trace:
#0 C:\inetpub\wwwroot\spotweb\lib\services\Image\Services_Image_Chart.php(28): pData->__construct()
#1 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(108): Services_Image_Chart->renderChart('3Dpie', 'Spots per categ...', Array, Array)
#2 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(60): Services_Providers_Statistics->createStatsPerCategory('')
#3 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(36): Services_Providers_Statistics->renderStatImage('spotspercategor...', '')
#4 C:\inetpub\wwwroot\spotweb\retrieve.php(250): Services_Providers_Statistics->createAllStatistics()
#5 {main}
  thrown in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 80
```
