### ISSUE TITLE
PHP Warning:  Illegal string offset on retrieving full comments 

### ISSUE THREAD

**Issue by sredXNY** [spotweb/spotweb#265]
Hi everyone, I just installed Spotweb and now I'm facing a problem when I run the retriever. Actually  I noticed that I get a warning when `retrieve_full_comments` in the `settings `table is set to 1. This is what I get:

```
Retrieving 14911450 till 14911453PHP Warning:  Illegal string offset 'exponent'                                                                                         in /....myprojectPath.../lib/services/Nntp/Services_Nntp_SpotRead                                                                                        ing.php on line 39
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Nntp/Services_Nntp_SpotReading.php on line 40
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 28
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 29
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 28
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 29
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Nntp/Services_Nntp_SpotReading.php on line 39
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Nntp/Services_Nntp_SpotReading.php on line 40
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 28
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 29
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 28
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 29
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Nntp/Services_Nntp_SpotReading.php on line 39
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Nntp/Services_Nntp_SpotReading.php on line 40
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 28
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 29
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 23
PHP Warning:  Illegal string offset 'modulo' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 28
PHP Warning:  Illegal string offset 'exponent' in /....myprojectPath.../lib/services/Signing/Services_Signing_Openssl.php on line 29
, found 3 comments in 0.29 seconds
Processed a total of 3 comments
Finished retrieving comments.

```

I checked the file and there is verifying with the RSA key, then in the database the `rsa_keys` is not empty and I don't know what is happening then as the SSL extension is loaded. Should I worry about it? what can I do to throw off of the warning? I have PHP7 in Ubuntu 16.04 enviroment. Thanks!

**Comment by mesa57** [comment]
Already reported here : 
https://github.com/spotweb/spotweb/issues/246

**Comment by mesa57** [comment]
Solved in last commit

**Comment by sredXNY** [comment]
Hey, great! It worked. Just one thing, you set: `'user-key' => array('exponent' => '', modulo => ''),` instead of  `'user-key' => array('exponent' => '', 'modulo' => ''),` you missed the quotes, thanks!!

**Comment by mesa57** [comment]
Haha, ok, I will correct it. Anyway, it worked during testing.
