### ISSUE TITLE
Unable to export and import filters

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#489]
I'm trying to migrate to a new spotweb server and everything is up and running again, but the only thing I can't do is restore my filters.
When I export I get an XML file with all filters and when I try to upload that in the new server it show me this first
![image](https://user-images.githubusercontent.com/4103090/77734617-4b62bc80-7009-11ea-91ab-0122099af906.png)

No matter what I fill in I will get
```
Warning: array_merge(): Argument #1 is not an array in /var/www/spotweb.mgdn.nl/public/lib/services/User/Services_User_Filters.php on line 60
{"result":"failure","data":[],"info":[],"warnings":[],"errors":["Invalid filter name"]}
```

After the filters are imported but don't work. Some will not do anything while others if selected also select other filters at the same time.

If I go to preferences and try to change the original filters, it looks like somthing wants to happen but nothing does
![image](https://user-images.githubusercontent.com/4103090/77734886-cf1ca900-7009-11ea-8052-e8e9108df07f.png)

**Comment by Sweepr** [comment]
Which branch?

**Comment by Sweepr** [comment]
If there any major difference in build-up if you export the filters of the new spotweb instance and compare that with the exported filters of your old spotweb?

**Comment by Sweepr** [comment]
"Invalid filter name"

But which one is that?

**Comment by Rouzax** [comment]
First question, which is really good because I though both were on Develop but that was not the case.
Now they are both on develop and still the same issue.

Second, not really I just added a few filters to the original ones

Third, That is the weird thing the export contains all filters and when I import it is importing all of them but it still asks me name it as a single one.

I think I'll just recreate them, only added 8 or so.

PS: can you go to config -> change preferences and select a filter and click change?
Does that do something for you?

**Comment by Sweepr** [comment]
I'm not in the opportunity to do any testing since i'm afk.

I can do so later today or tomorrow.

**Comment by Rouzax** [comment]
> I'm not in the opportunity to do any testing since i'm afk.
> 
> I can do so later today or tomorrow.

No worries, I'm recreating them as we speak so it is not urgent :)

**Comment by Sweepr** [comment]
Still have to investigate this, have to verify if there is not an actual issue, 

Can you provide me info about your browser and PHP version?

**Comment by Rouzax** [comment]
Chrome
PHP old server
```
PHP 7.2.7 (cli) (built: Jun 19 2018 23:13:48) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

PHP New server
```
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by Sweepr** [comment]
And does that also happen with for example Firefox and/or plugins disabled e.g. safemode?

**Comment by Rouzax** [comment]
> And does that also happen with for example Firefox and/or plugins disabled e.g. safemode?

Yes, just tried on new and old server with the same result.

**Comment by Sweepr** [comment]
Ok, i'll have to check this later on my own install.

**Comment by Sweepr** [comment]
You could try to initialize $filter as array first:

Between line 59 and 60.. 

after { 
add: $filter = array();
before $filter = array_merge

In file:

/var/www/spotweb.mgdn.nl/public/lib/services/User/Services_User_Filters.php on line 60

Let me know if that fixes anything

**Comment by Sweepr** [comment]
I have confirmed this on my own install, both Develop as Master branch have this issue, so we can rule out recent change's to Develop branch caused this.

Further more, i can export the filters, and edit them using:

![image](https://user-images.githubusercontent.com/2857865/77780725-bbe2fb00-7054-11ea-8996-ddf549a35da1.png)

And when i uploaded them i got exactly the same warnings as you.

![image](https://user-images.githubusercontent.com/2857865/77817146-f1c1c700-70c8-11ea-967b-c29b0f999b63.png)

Not sure what is casuing this, but the filters do change.

By means of test i exported the filters, moved some things around using Spotweb Filter creator

![image](https://user-images.githubusercontent.com/2857865/77817170-2c2b6400-70c9-11ea-8a0b-88bd59ee76b0.png)

And the change's were taken by Spotweb.

![image](https://user-images.githubusercontent.com/2857865/77817178-3e0d0700-70c9-11ea-9b3f-eb5c3a778ccc.png)

**Comment by Sweepr** [comment]
I have pushed some change's to the Dev branch, can you confirm if that solves your issue?

**Comment by Sweepr** [comment]
No response from @Rouzax so i assume all is good, therefor i will close this issue for now, feel free to re-open if needed.

**Comment by Rouzax** [comment]
Sorry, didn't have time yet.
Just did a git pull but I still can't Change a filter from Preferences.

Did try to export and import in on my old server and it looks to be okay.
Thank you.

**Comment by Sweepr** [comment]
@Rouzax no problem, do you mean this?

![image](https://user-images.githubusercontent.com/2857865/77852496-48212980-71df-11ea-8f4f-98996e641029.png)

Before:
![image](https://user-images.githubusercontent.com/2857865/77852511-5c652680-71df-11ea-8c6d-c97ac1b65574.png)
After
![image](https://user-images.githubusercontent.com/2857865/77852506-54a58200-71df-11ea-86f2-4e347c2203e9.png)

Does your user have the correct permissions?

![image](https://user-images.githubusercontent.com/2857865/77852568-a0f0c200-71df-11ea-9c36-6730a8d0661d.png)

**Comment by Rouzax** [comment]
Yes, but I now see my wrong assumption 😳
Change here is just the name and the icon not the actual search query.

**Comment by Sweepr** [comment]
Indeed, are you familiar with this program?

https://www.brainbytez.nl/spotweb-filter-creator/

Spotweb Filter Creator is a tool for creating Spotweb Filter XML files easier.

After starting Spotweb Creator, a new filter can be created by clicking the (+) Add button.
In the Filters tree below, an item with the selected filter name and icon appears.

On the right, in the Contents tree, the available categories appear.

By ticking the box for a category, it will be linked to the selected filter in the Filters tree.
If all filters satisfactorily have been created, it can be saved in XML format with the Save / Save As .. button (eg MyFilters.xml).

The saved filter file (MyFilters.xml) can then be uploaded to Spotweb at the filter preferences.

**Comment by Rouzax** [comment]
Thanks will have a look
